name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Imposta ambiente
      run: echo "Inserire qui il proprio script di build/test"
    - name: Esegui test
      run: echo "es: pytest"
